# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 06:38
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_users_filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUserStats',
            fields=[
            ],
            options={
                'verbose_name': 'Github User Stats',
                'proxy': True,
                'verbose_name_plural': 'Github User Stats',
                'indexes': [],
            },
            bases=('github_users_filter.githubuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='searchapicalllog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='searchapicalllog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
